### ISSUE TITLE
Разные интервалы для отправки метрик.

### ISSUE THREAD

**Issue by mnemchinov** [freewms/PDE#25]
Сейчас, на сколько я понимаю, все метрики рассчитываются и отправляются один раз в секунду. Требуется сделать возможность для метрики указывать интервал отправки. Например, есть метрика отправки критических сообщений за последнюю минуту. Соответственно, устанавливаем интервал 60 сек. и настраиваем сбор сообщений ошибок ЖР за предывдущую минуту.

**Comment by freewms** [comment]
Уже в работе.
Ограничения: предполагается реализовать посредством индивидуальных регламентных заданий. Как следствие - отсчет времени "паузы" между запусками начинается по окончанию регламента, а не его началу. Как следствие - паузы будут складываться как сумма времени повтора регламентного задания и времени вычисления метрики.

**Comment by freewms** [comment]
Плюс #5
